apiVersion: v1
kind: Secret
metadata:
  name: eagle-env
  labels:
    {{- include "eagle.labels" . | nindent 4 }}
type: Opaque
stringData:
  dtrack_db: jdbc:postgresql://{{ .Values.db_host }}:5432/dtrack
  rundeck_db: jdbc:postgresql://{{ .Values.db_host }}:5432/rundeck
  terraboard_db: jdbc:postgresql://{{ .Values.db_host }}:5432/terraboard
  db_user: {{ .Values.db_user }}
  db_password: {{ .Values.db_password }}
  db_host: {{ .Values.db_host }}
  dojo_secret_key: {{ .Values.dojo_secret_key }}
  dojo_db: postgresql://{{ .Values.db_user }}:{{ .Values.db_password }}@{{ .Values.db_host }}:5432/defectdojo
  rundeck_grails_url: https://{{ .Values.ingress.rundeck_host }}
  terraboard_grails_url: https://{{ .Values.ingress.terraboard_host }}
  rundeck_worker_password: {{ .Values.rundeck_worker_password }}
data:
  dojo_aes_key: {{ .Values.dojo_aes_key }}
  